# Generated by Django 5.2.5 on 2025-08-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_at',
            new_name='published_date',
        ),
    ]
